package profile

import (
	"fmt"
	"sort"
	"strings"

	"psycho/modules/analyze"
)

// NarrativeGenerator produces a human-readable narrative from a Profile.
type NarrativeGenerator interface {
	GenerateSynthesis(profile Profile) string
}

// TemplateNarrativeGenerator produces narrative text using predefined templates.
type TemplateNarrativeGenerator struct{}

func NewTemplateNarrativeGenerator() *TemplateNarrativeGenerator {
	return &TemplateNarrativeGenerator{}
}

func (g *TemplateNarrativeGenerator) GenerateSynthesis(profile Profile) string {
	out := "## Psychological Profile\n\n"
	out += fmt.Sprintf("**Confidence level:** %s\n\n", profile.ConfidenceFlag)

	out += "### Big Five (OCEAN)\n\n"
	for _, name := range []string{"openness", "conscientiousness", "extraversion", "agreeableness", "neuroticism"} {
		t := profile.Traits[name]
		out += fmt.Sprintf("**%s:** %.2f (%s), %s percentile (rough score range: %.2f–%.2f)\n\n",
			analyze.DimensionDisplayName(name), t.Score, analyze.DimensionLabel(name, t.Score), analyze.Ordinal(t.Percentile), t.ConfidenceInterval[0], t.ConfidenceInterval[1])
	}

	out += "### Regulatory Focus\n\n"
	rf := profile.Traits["regulatory_focus"]
	out += fmt.Sprintf("**Regulatory Focus:** %.2f (%s), %s percentile (rough score range: %.2f–%.2f)\n\n",
		rf.Score, analyze.DimensionLabel("regulatory_focus", rf.Score), analyze.Ordinal(rf.Percentile), rf.ConfidenceInterval[0], rf.ConfidenceInterval[1])

	out += "### Need for Cognition\n\n"
	nc := profile.Traits["need_for_cognition"]
	out += fmt.Sprintf("**Need for Cognition:** %.2f (%s), %s percentile (rough score range: %.2f–%.2f)\n\n",
		nc.Score, analyze.DimensionLabel("need_for_cognition", nc.Score), analyze.Ordinal(nc.Percentile), nc.ConfidenceInterval[0], nc.ConfidenceInterval[1])

	out += "### Cognitive Style\n\n"
	cs := profile.Traits["cognitive_style"]
	out += fmt.Sprintf("**Cognitive Style:** %.2f (%s), %s percentile (rough score range: %.2f–%.2f)\n\n",
		cs.Score, analyze.DimensionLabel("cognitive_style", cs.Score), analyze.Ordinal(cs.Percentile), cs.ConfidenceInterval[0], cs.ConfidenceInterval[1])

	out += "### Need for Closure\n\n"
	ncl := profile.Traits["need_for_closure"]
	out += fmt.Sprintf("**Need for Closure:** %.2f (%s), %s percentile (rough score range: %.2f–%.2f)\n\n",
		ncl.Score, analyze.DimensionLabel("need_for_closure", ncl.Score), analyze.Ordinal(ncl.Percentile), ncl.ConfidenceInterval[0], ncl.ConfidenceInterval[1])

	if len(profile.Values) > 0 {
		out += "### Schwartz Value Orientation\n\n"
		keys := make([]string, 0, len(profile.Values))
		for k := range profile.Values {
			keys = append(keys, k)
		}
		sort.Slice(keys, func(i, j int) bool {
			if profile.Values[keys[i]] == profile.Values[keys[j]] {
				return keys[i] < keys[j]
			}
			return profile.Values[keys[i]] > profile.Values[keys[j]]
		})
		for _, k := range keys {
			pct := profile.Values[k]
			dn := analyze.ValueDisplayName(analyze.ValueCategory(k))
			if words := profile.ValueEvidence[k]; len(words) > 0 {
				out += fmt.Sprintf("- **%s:** %.2f%% of words (%s)\n", dn, pct, strings.Join(words, ", "))
			} else {
				out += fmt.Sprintf("- **%s:** %.2f%% of words\n", dn, pct)
			}
		}
		out += "\n"
	}

	out += "### Summary Variables\n\n"
	sv := profile.Summary
	out += fmt.Sprintf("- **Analytical Thinking:** %.2f, %s\n", sv.AnalyticalThinking, analyze.SummaryBandFormal("analytical_thinking", sv.AnalyticalThinking))
	out += fmt.Sprintf("- **Clout:** %.2f, %s\n", sv.Clout, analyze.SummaryBandFormal("clout", sv.Clout))
	out += fmt.Sprintf("- **Authenticity:** %.2f, %s\n", sv.Authenticity, analyze.SummaryBandFormal("authenticity", sv.Authenticity))
	out += fmt.Sprintf("- **Emotional Tone:** %.2f, %s\n", sv.EmotionalTone, analyze.SummaryTone(sv.EmotionalTone))

	out += "\n---\n"
	out += "*Generated by Psycho. Project-defined text proxies, not validated personality or clinical measures.*"
	return out
}
