package profile

import (
	"fmt"

	"psycho/modules/analyze"
)

// NarrativeGenerator produces a human-readable narrative from a Profile.
type NarrativeGenerator interface {
	GenerateSynthesis(profile Profile) string
}

// TemplateNarrativeGenerator produces narrative text using predefined templates.
type TemplateNarrativeGenerator struct{}

func NewTemplateNarrativeGenerator() *TemplateNarrativeGenerator {
	return &TemplateNarrativeGenerator{}
}

func (g *TemplateNarrativeGenerator) GenerateSynthesis(profile Profile) string {
	out := "## Psychological Profile\n\n"
	out += fmt.Sprintf("**Confidence level:** %s\n\n", profile.ConfidenceFlag)

	out += "### Big Five (OCEAN)\n\n"
	for _, name := range []string{"openness", "conscientiousness", "extraversion", "agreeableness", "neuroticism"} {
		t := profile.Traits[name]
		out += fmt.Sprintf("**%s:** %.2f (%s) — %dth percentile (95%% CI: %.2f–%.2f)\n\n",
			traitDisplayName(name), t.Score, traitLabel(name, t.Score), t.Percentile, t.ConfidenceInterval[0], t.ConfidenceInterval[1])
	}

	out += "### Regulatory Focus\n\n"
	rf := profile.Traits["regulatory_focus"]
	out += fmt.Sprintf("**Regulatory Focus:** %.2f (%s) — %dth percentile (95%% CI: %.2f–%.2f)\n\n",
		rf.Score, traitLabel("regulatory_focus", rf.Score), rf.Percentile, rf.ConfidenceInterval[0], rf.ConfidenceInterval[1])

	out += "### Need for Cognition\n\n"
	nc := profile.Traits["need_for_cognition"]
	out += fmt.Sprintf("**Need for Cognition:** %.2f (%s) — %dth percentile (95%% CI: %.2f–%.2f)\n\n",
		nc.Score, traitLabel("need_for_cognition", nc.Score), nc.Percentile, nc.ConfidenceInterval[0], nc.ConfidenceInterval[1])

	out += "### Summary Variables\n\n"
	sv := profile.Summary
	out += fmt.Sprintf("- **Analytical Thinking:** %.2f — %s\n", sv.AnalyticalThinking, summaryLabel(sv.AnalyticalThinking, "highly analytical", "intuitive"))
	out += fmt.Sprintf("- **Clout:** %.2f — %s\n", sv.Clout, summaryLabel(sv.Clout, "confident/dominant", "submissive/uncertain"))
	out += fmt.Sprintf("- **Authenticity:** %.2f — %s\n", sv.Authenticity, summaryLabel(sv.Authenticity, "personal/honest", "guarded/distant"))
	out += fmt.Sprintf("- **Emotional Tone:** %.2f — %s\n", sv.EmotionalTone, toneLabel(sv.EmotionalTone))

	out += "\n---\n"
	out += "*Generated by Psycho — template-based synthesis. Not a clinical assessment.*"
	return out
}

func traitDisplayName(key string) string {
	names := map[string]string{
		"openness":           "Openness",
		"conscientiousness":  "Conscientiousness",
		"extraversion":       "Extraversion",
		"agreeableness":      "Agreeableness",
		"neuroticism":        "Neuroticism",
		"regulatory_focus":   "Regulatory Focus",
		"need_for_cognition": "Need for Cognition",
	}
	if n, ok := names[key]; ok {
		return n
	}
	return key
}

func traitLabel(name string, score float64) string {
	if name == "regulatory_focus" {
		return analyze.ComputeRegulatoryFocusLabel(score)
	}
	if name == "need_for_cognition" {
		return analyze.ComputeNeedForCognitionLabel(score)
	}
	if score >= 0.65 {
		return "high"
	}
	if score < 0.35 {
		return "low"
	}
	return "moderate"
}

func summaryLabel(score float64, high, low string) string {
	if score >= 0.65 {
		return high
	}
	if score < 0.35 {
		return low
	}
	return "moderate"
}

func toneLabel(score float64) string {
	if score >= 0.65 {
		return "positive"
	}
	if score < 0.35 {
		return "negative"
	}
	return "neutral"
}
