package profile

import (
	"fmt"
	"strings"

	maroto "github.com/johnfercher/maroto/v2"
	"github.com/johnfercher/maroto/v2/pkg/components/text"
	"github.com/johnfercher/maroto/v2/pkg/config"
	"github.com/johnfercher/maroto/v2/pkg/consts/align"
	"github.com/johnfercher/maroto/v2/pkg/consts/fontstyle"
	"github.com/johnfercher/maroto/v2/pkg/consts/pagesize"
	"github.com/johnfercher/maroto/v2/pkg/core"
	"github.com/johnfercher/maroto/v2/pkg/props"

	"psycho/modules/analyze"
)

type MarotoPDFGenerator struct{}

func NewMarotoPDFGenerator() *MarotoPDFGenerator {
	return &MarotoPDFGenerator{}
}

func (g *MarotoPDFGenerator) Generate(p Profile) ([]byte, error) {
	cfg := config.NewBuilder().
		WithPageSize(pagesize.A4).
		WithLeftMargin(20).
		WithTopMargin(20).
		WithRightMargin(20).
		WithBottomMargin(20).
		WithAuthor("Psycho", false).
		WithTitle("Your writing profile", false).
		Build()

	m := maroto.New(cfg)

	allTraits := []string{
		"openness", "conscientiousness", "extraversion", "agreeableness", "neuroticism",
		"regulatory_focus", "need_for_cognition", "cognitive_style", "need_for_closure",
	}

	m.AddRow(14, text.NewCol(12, "Your writing profile",
		props.Text{Style: fontstyle.Bold, Size: 16, Align: align.Center}))
	m.AddRow(6, text.NewCol(12, fmt.Sprintf("Confidence in this reading: %s  |  Analysis ID: %s", confidenceLabel(p.ConfidenceFlag), p.AnalysisID),
		props.Text{Size: 8, Align: align.Center}))
	m.AddAutoRow(text.NewCol(12, "Read this first. "+analyze.ReadingCaveat,
		props.Text{Size: 8, Style: fontstyle.Bold}))
	m.AddRow(2, text.NewCol(12, ""))
	m.AddRow(6, text.NewCol(12, "Generated by Psycho. Project-defined text proxies, not validated personality or clinical measures.",
		props.Text{Size: 7, Align: align.Center, Style: fontstyle.Italic}))

	m.AddRow(4, text.NewCol(12, ""))

	// Present saved numbers with current copy; old saved narratives can contain
	// the former repeated scores and ranges. Never rerun inference.
	narrative := NewTemplateNarrativeGenerator().GenerateSynthesis(p)
	g.renderNarrative(m, strings.TrimPrefix(narrative, "## Your writing profile\n\n"))
	m.AddRow(10, text.NewCol(12, ""))
	m.AddRow(8, text.NewCol(12, "Linguistic Evidence", props.Text{Style: fontstyle.Bold, Size: 12}))
	m.AddRow(4, text.NewCol(12, "Contribution = share of words in a dictionary category × per-percentage-point weight. Values below are rounded for display; recorded operands are used when available.",
		props.Text{Size: 7, Style: fontstyle.Italic}))
	m.AddRow(4, text.NewCol(12, ""))
	for _, name := range allTraits {
		t, ok := p.Traits[name]
		if !ok {
			continue
		}
		m.AddRow(6, text.NewCol(12, analyze.DimensionDisplayName(name), props.Text{Size: 9}))
		if p.CalculationDetails != nil && p.CalculationDetails.Traits[name] != nil {
			c := p.CalculationDetails.Traits[name]
			m.AddAutoRow(text.NewCol(12, fmt.Sprintf("Baseline %.4f + contributions %+.4f; model %.2f; calibration %+.4f; final %.2f", c.Baseline, c.ContributionTotal, c.ModelScore, c.CalibrationOffset, c.FinalScore), props.Text{Size: 8}))
			for _, term := range c.Terms {
				m.AddAutoRow(text.NewCol(12, fmt.Sprintf("%s: %d/%d words; %.4f%% x %+.4f = %+.4f", term.Category, term.MatchedCount, term.TotalWords, term.WordPercent, term.Weight, term.Contribution), props.Text{Size: 8}))
			}
		} else {
			m.AddAutoRow(text.NewCol(12, "Complete calculation details were not recorded for this analysis.", props.Text{Size: 8}))
			for _, c := range t.Evidence {
				m.AddAutoRow(text.NewCol(12, fmt.Sprintf("%s: %.2f%% of words x %+.3f = %+.4f", c.Category, c.WordPercent, c.Weight, c.Contribution), props.Text{Size: 8}))
			}
		}
	}

	doc, err := m.Generate()
	if err != nil {
		return nil, fmt.Errorf("generate pdf: %w", err)
	}
	return doc.GetBytes(), nil
}

// renderNarrative converts the narrative's lightweight Markdown (##/###
// headings, **bold** labels, - bullets, --- rules) into maroto rows.
// Maroto has no inline styling, so emphasis markers are stripped rather
// than printed literally.
func (g *MarotoPDFGenerator) renderNarrative(m core.Maroto, narrative string) {
	for _, line := range strings.Split(narrative, "\n") {
		trimmed := strings.TrimSpace(line)
		switch {
		case trimmed == "":
			continue
		case strings.HasPrefix(trimmed, "### "):
			m.AddRow(6, text.NewCol(12, strings.TrimPrefix(trimmed, "### "),
				props.Text{Style: fontstyle.Bold, Size: 11}))
		case strings.HasPrefix(trimmed, "## "):
			m.AddRow(8, text.NewCol(12, strings.TrimPrefix(trimmed, "## "),
				props.Text{Style: fontstyle.Bold, Size: 12}))
		case trimmed == "---":
			m.AddRow(3, text.NewCol(12, ""))
		case strings.HasPrefix(trimmed, "- "):
			m.AddAutoRow(text.NewCol(12, "• "+stripEmphasis(strings.TrimPrefix(trimmed, "- ")),
				props.Text{Size: 9}))
		default:
			m.AddAutoRow(text.NewCol(12, stripEmphasis(trimmed), props.Text{Size: 9}))
		}
	}
}

func stripEmphasis(s string) string {
	s = strings.ReplaceAll(s, "**", "")
	return strings.ReplaceAll(s, "*", "")
}

// confidenceLabel turns the stored lowercase flag into the capitalized word
// the HTML report shows.
func confidenceLabel(flag string) string {
	switch flag {
	case "low":
		return "Low"
	case "high":
		return "High"
	default:
		return "Medium"
	}
}
