package profile

import (
	"fmt"
	"sort"

	maroto "github.com/johnfercher/maroto/v2"
	"github.com/johnfercher/maroto/v2/pkg/components/text"
	"github.com/johnfercher/maroto/v2/pkg/config"
	"github.com/johnfercher/maroto/v2/pkg/consts/align"
	"github.com/johnfercher/maroto/v2/pkg/consts/fontstyle"
	"github.com/johnfercher/maroto/v2/pkg/consts/pagesize"
	"github.com/johnfercher/maroto/v2/pkg/props"

	"psycho/modules/analyze"
)

type MarotoPDFGenerator struct{}

func NewMarotoPDFGenerator() *MarotoPDFGenerator {
	return &MarotoPDFGenerator{}
}

func (g *MarotoPDFGenerator) Generate(p Profile) ([]byte, error) {
	cfg := config.NewBuilder().
		WithPageSize(pagesize.A4).
		WithLeftMargin(20).
		WithTopMargin(20).
		WithRightMargin(20).
		WithBottomMargin(20).
		WithAuthor("Psycho", false).
		WithTitle("Psychological Profile", false).
		Build()

	m := maroto.New(cfg)

	allTraits := []string{
		"openness", "conscientiousness", "extraversion", "agreeableness", "neuroticism",
		"regulatory_focus", "need_for_cognition", "cognitive_style", "need_for_closure",
	}

	m.AddRow(14, text.NewCol(12, "Psychological Profile",
		props.Text{Style: fontstyle.Bold, Size: 16, Align: align.Center}))
	m.AddRow(6, text.NewCol(12, fmt.Sprintf("Confidence level: %s  |  Analysis ID: %s", p.ConfidenceFlag, p.AnalysisID),
		props.Text{Size: 8, Align: align.Center}))
	m.AddRow(6, text.NewCol(12, "Generated by Psycho — template-based synthesis. Not a clinical assessment.",
		props.Text{Size: 7, Align: align.Center, Style: fontstyle.Italic}))

	m.AddRow(4, text.NewCol(12, ""))

	if p.Narrative != "" {
		m.AddRow(8, text.NewCol(12, "Summary", props.Text{Style: fontstyle.Bold, Size: 12}))
		m.AddRow(4, text.NewCol(12, ""))
		m.AddAutoRow(text.NewCol(12, p.Narrative, props.Text{Size: 9}))
		m.AddRow(6, text.NewCol(12, ""))
	}

	m.AddRow(8, text.NewCol(12, "At a Glance", props.Text{Style: fontstyle.Bold, Size: 12}))
	m.AddRow(4, text.NewCol(12, ""))
	for _, name := range allTraits {
		t, ok := p.Traits[name]
		if !ok || len(t.ConfidenceInterval) < 2 {
			continue
		}
		m.AddRow(5, text.NewCol(12, fmt.Sprintf("%s: %s", traitDisplayName(name), traitLabel(name, t.Score)),
			props.Text{Size: 9}))
	}

	if len(p.Values) > 0 {
		m.AddRow(6, text.NewCol(12, ""))
		m.AddRow(8, text.NewCol(12, "Schwartz Value Orientation (ranked)",
			props.Text{Style: fontstyle.Bold, Size: 12}))
		m.AddRow(4, text.NewCol(12, ""))

		keys := make([]string, 0, len(p.Values))
		for k := range p.Values {
			keys = append(keys, k)
		}
		sort.Slice(keys, func(i, j int) bool {
			return p.Values[keys[i]] > p.Values[keys[j]]
		})
		for i, k := range keys {
			dn := analyze.ValueDisplayName(analyze.ValueCategory(k))
			m.AddRow(5, text.NewCol(12, fmt.Sprintf("%d. %s", i+1, dn), props.Text{Size: 9}))
		}
	}

	m.AddRow(6, text.NewCol(12, ""))
	m.AddRow(8, text.NewCol(12, "Summary Variables",
		props.Text{Style: fontstyle.Bold, Size: 12}))
	m.AddRow(4, text.NewCol(12, ""))
	sv := p.Summary
	m.AddRow(5, text.NewCol(12, fmt.Sprintf("Analytical Thinking: %s",
		summaryLabel(sv.AnalyticalThinking, "highly analytical", "intuitive")),
		props.Text{Size: 9}))
	m.AddRow(5, text.NewCol(12, fmt.Sprintf("Clout: %s",
		summaryLabel(sv.Clout, "confident/dominant", "submissive/uncertain")),
		props.Text{Size: 9}))
	m.AddRow(5, text.NewCol(12, fmt.Sprintf("Authenticity: %s",
		summaryLabel(sv.Authenticity, "personal/honest", "guarded/distant")),
		props.Text{Size: 9}))
	m.AddRow(5, text.NewCol(12, fmt.Sprintf("Emotional Tone: %s", toneLabel(sv.EmotionalTone)),
		props.Text{Size: 9}))

	m.AddRow(10, text.NewCol(12, ""))
	m.AddRow(8, text.NewCol(12, "Statistical Detail", props.Text{Style: fontstyle.Bold, Size: 12}))
	m.AddRow(4, text.NewCol(12, "Percentile is relative to the reference sample; the 95% CI reflects measurement uncertainty from text coverage.",
		props.Text{Size: 7, Style: fontstyle.Italic}))
	m.AddRow(4, text.NewCol(12, ""))
	for _, name := range allTraits {
		t, ok := p.Traits[name]
		if !ok || len(t.ConfidenceInterval) < 2 {
			continue
		}
		line := fmt.Sprintf("%s: %.2f — %dth percentile (95%% CI: %.2f–%.2f)",
			traitDisplayName(name), t.Score, t.Percentile, t.ConfidenceInterval[0], t.ConfidenceInterval[1])
		m.AddRow(5, text.NewCol(12, line, props.Text{Size: 7}))
	}

	doc, err := m.Generate()
	if err != nil {
		return nil, fmt.Errorf("generate pdf: %w", err)
	}
	return doc.GetBytes(), nil
}
