package profile

import (
	"fmt"
	"sort"

	maroto "github.com/johnfercher/maroto/v2"
	"github.com/johnfercher/maroto/v2/pkg/components/text"
	"github.com/johnfercher/maroto/v2/pkg/config"
	"github.com/johnfercher/maroto/v2/pkg/consts/align"
	"github.com/johnfercher/maroto/v2/pkg/consts/fontstyle"
	"github.com/johnfercher/maroto/v2/pkg/consts/pagesize"
	"github.com/johnfercher/maroto/v2/pkg/core"
	"github.com/johnfercher/maroto/v2/pkg/props"

	"psycho/modules/analyze"
)

type MarotoPDFGenerator struct{}

func NewMarotoPDFGenerator() *MarotoPDFGenerator {
	return &MarotoPDFGenerator{}
}

func (g *MarotoPDFGenerator) Generate(p Profile) ([]byte, error) {
	cfg := config.NewBuilder().
		WithPageSize(pagesize.A4).
		WithLeftMargin(20).
		WithTopMargin(20).
		WithRightMargin(20).
		WithBottomMargin(20).
		WithAuthor("Psycho", false).
		WithTitle("Psychological Profile", false).
		Build()

	m := maroto.New(cfg)

	m.AddRow(14, text.NewCol(12, "Psychological Profile",
		props.Text{Style: fontstyle.Bold, Size: 16, Align: align.Center}))
	m.AddRow(8, text.NewCol(12, fmt.Sprintf("Confidence level: %s  |  Analysis ID: %s",
		p.ConfidenceFlag, p.AnalysisID),
		props.Text{Size: 8, Align: align.Center}))

	m.AddRow(4, text.NewCol(12, ""))

	m.AddRow(8, text.NewCol(12, "Big Five (OCEAN)",
		props.Text{Style: fontstyle.Bold, Size: 12}))
	m.AddRow(4, text.NewCol(12, ""))

	for _, name := range []string{"openness", "conscientiousness", "extraversion", "agreeableness", "neuroticism"} {
		t, ok := p.Traits[name]
		if !ok || len(t.ConfidenceInterval) < 2 {
			continue
		}
		line := fmt.Sprintf("%s: %.2f (%s) — %dth percentile (95%% CI: %.2f–%.2f)",
			traitDisplayName(name), t.Score, traitLabel(name, t.Score),
			t.Percentile, t.ConfidenceInterval[0], t.ConfidenceInterval[1])
		m.AddAutoRow(text.NewCol(12, line, props.Text{Size: 9}))
	}

	addTraitSection(m, p, "Regulatory Focus", "regulatory_focus")
	addTraitSection(m, p, "Need for Cognition", "need_for_cognition")
	addTraitSection(m, p, "Cognitive Style", "cognitive_style")
	addTraitSection(m, p, "Need for Closure", "need_for_closure")

	if len(p.Values) > 0 {
		m.AddRow(6, text.NewCol(12, ""))
		m.AddRow(8, text.NewCol(12, "Schwartz Value Orientation",
			props.Text{Style: fontstyle.Bold, Size: 12}))
		m.AddRow(4, text.NewCol(12, ""))

		keys := make([]string, 0, len(p.Values))
		for k := range p.Values {
			keys = append(keys, k)
		}
		sort.Slice(keys, func(i, j int) bool {
			return p.Values[keys[i]] > p.Values[keys[j]]
		})
		for _, k := range keys {
			pct := p.Values[k]
			dn := analyze.ValueDisplayName(analyze.ValueCategory(k))
			m.AddAutoRow(text.NewCol(12, fmt.Sprintf("%s: %.2f%% of words", dn, pct),
				props.Text{Size: 9}))
		}
	}

	m.AddRow(6, text.NewCol(12, ""))
	m.AddRow(8, text.NewCol(12, "Summary Variables",
		props.Text{Style: fontstyle.Bold, Size: 12}))
	m.AddRow(4, text.NewCol(12, ""))
	sv := p.Summary
	m.AddAutoRow(text.NewCol(12, fmt.Sprintf("Analytical Thinking: %.2f — %s", sv.AnalyticalThinking,
		summaryLabel(sv.AnalyticalThinking, "highly analytical", "intuitive")),
		props.Text{Size: 9}))
	m.AddAutoRow(text.NewCol(12, fmt.Sprintf("Clout: %.2f — %s", sv.Clout,
		summaryLabel(sv.Clout, "confident/dominant", "submissive/uncertain")),
		props.Text{Size: 9}))
	m.AddAutoRow(text.NewCol(12, fmt.Sprintf("Authenticity: %.2f — %s", sv.Authenticity,
		summaryLabel(sv.Authenticity, "personal/honest", "guarded/distant")),
		props.Text{Size: 9}))
	m.AddAutoRow(text.NewCol(12, fmt.Sprintf("Emotional Tone: %.2f — %s", sv.EmotionalTone, toneLabel(sv.EmotionalTone)),
		props.Text{Size: 9}))

	if p.Narrative != "" {
		m.AddRow(6, text.NewCol(12, ""))
		m.AddRow(8, text.NewCol(12, "Narrative",
			props.Text{Style: fontstyle.Bold, Size: 12}))
		m.AddRow(4, text.NewCol(12, ""))
		m.AddAutoRow(text.NewCol(12, p.Narrative, props.Text{Size: 8}))
	}

	m.AddRow(10, text.NewCol(12, ""))
	m.AddRow(6, text.NewCol(12, "Generated by Psycho — template-based synthesis. Not a clinical assessment.",
		props.Text{Size: 7, Align: align.Center}))

	doc, err := m.Generate()
	if err != nil {
		return nil, fmt.Errorf("generate pdf: %w", err)
	}
	return doc.GetBytes(), nil
}

func addTraitSection(m core.Maroto, p Profile, heading, key string) {
	m.AddRow(6, text.NewCol(12, ""))
	m.AddRow(8, text.NewCol(12, heading, props.Text{Style: fontstyle.Bold, Size: 12}))
	m.AddRow(4, text.NewCol(12, ""))

	t, ok := p.Traits[key]
	if !ok || len(t.ConfidenceInterval) < 2 {
		return
	}

	m.AddAutoRow(text.NewCol(12, fmt.Sprintf("%s: %.2f (%s) — %dth percentile (95%% CI: %.2f–%.2f)",
		heading, t.Score, traitLabel(key, t.Score),
		t.Percentile, t.ConfidenceInterval[0], t.ConfidenceInterval[1]),
		props.Text{Size: 9}))
}
