app:
  http:
    port: "8080"
    read_timeout_in_second: 5
    write_timeout_in_second: 35
    idle_timeout_in_second: 120

middleware:
  timeout_in_second: 30
  logger:
    level: dev  # dev | prod

ingest:
  max_text_size: 1000000  # ~1 MB of text
  dir_path: "samples"  # directory read by /analyze-dir

analyze:
  dictionary_path: "modules/analyze/dictionary.json"

profile:
  db_path: "psycho.db"
